//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int orderid { get; set; }
        public string customerid { get; set; }
        public string productids { get; set; }
        public string quantity { get; set; }
        public string prices { get; set; }
        public Nullable<double> totalprice { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string orderstatus { get; set; }
        public string paymenttype { get; set; }
        public string paymentstatus { get; set; }
        public string deliverby { get; set; }
        public Nullable<System.DateTime> delivereddate { get; set; }
        public Nullable<System.DateTime> shippingdate { get; set; }
        public string courierno { get; set; }
        public string couriertype { get; set; }
        public string shippingaddress { get; set; }
    }
}
