//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_category
    {
        public int categoryid { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string type { get; set; }
    }
}
