//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_master
    {
        public int productid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string productname { get; set; }
        public Nullable<double> mrp { get; set; }
        public Nullable<double> sellingprice { get; set; }
        public string brand { get; set; }
        public Nullable<int> quantity { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public string shortdescp { get; set; }
        public string longdescp { get; set; }
        public string productimage { get; set; }
        public string sellerid { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
        public string status { get; set; }
    }
}
