//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master
    {
        public string name { get; set; }
        public string emailid { get; set; }
        public string password { get; set; }
        public string securityquestion { get; set; }
        public string answer { get; set; }
    }
}
