//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_feedback
    {
        public int feedbackid { get; set; }
        public string name { get; set; }
        public string emailid { get; set; }
        public string contactno { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> dateofmsg { get; set; }
    }
}
